# Generated by Django 6.0.4 on 2026-04-12 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frase_original', models.TextField()),
                ('frase_traduzida', models.TextField()),
                ('categoria', models.CharField(choices=[('saudacao', 'Saudação'), ('saude', 'Saúde'), ('educacao', 'Educação'), ('comercio', 'Comércio'), ('governo', 'Governo'), ('emergencia', 'Emergência'), ('geral', 'Geral')], default='geral', max_length=20)),
                ('idioma_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frases', to='core.idioma')),
            ],
            options={
                'verbose_name': 'Frase',
                'verbose_name_plural': 'Frases',
                'unique_together': {('frase_original', 'idioma_destino')},
            },
        ),
        migrations.DeleteModel(
            name='FraseMedica',
        ),
    ]
