# Generated by Django 6.0.4 on 2026-04-12 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_frase_delete_frasemedica'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessao',
            old_name='idioma_paciente',
            new_name='idioma_falante',
        ),
        migrations.RenameField(
            model_name='sessao',
            old_name='medico',
            new_name='utilizador',
        ),
    ]
